// serviceB.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/serviceB/serviceB.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServiceB_BarB_FullMethodName = "/serviceB.ServiceB/BarB"
)

// ServiceBClient is the client API for ServiceB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 定义 ServiceB 服务
type ServiceBClient interface {
	// BarB 接口，接收 ReqB，返回 RespB
	BarB(ctx context.Context, in *ReqB, opts ...grpc.CallOption) (*RespB, error)
}

type serviceBClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceBClient(cc grpc.ClientConnInterface) ServiceBClient {
	return &serviceBClient{cc}
}

func (c *serviceBClient) BarB(ctx context.Context, in *ReqB, opts ...grpc.CallOption) (*RespB, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespB)
	err := c.cc.Invoke(ctx, ServiceB_BarB_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceBServer is the server API for ServiceB service.
// All implementations must embed UnimplementedServiceBServer
// for forward compatibility.
//
// 定义 ServiceB 服务
type ServiceBServer interface {
	// BarB 接口，接收 ReqB，返回 RespB
	BarB(context.Context, *ReqB) (*RespB, error)
	mustEmbedUnimplementedServiceBServer()
}

// UnimplementedServiceBServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceBServer struct{}

func (UnimplementedServiceBServer) BarB(context.Context, *ReqB) (*RespB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BarB not implemented")
}
func (UnimplementedServiceBServer) mustEmbedUnimplementedServiceBServer() {}
func (UnimplementedServiceBServer) testEmbeddedByValue()                  {}

// UnsafeServiceBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceBServer will
// result in compilation errors.
type UnsafeServiceBServer interface {
	mustEmbedUnimplementedServiceBServer()
}

func RegisterServiceBServer(s grpc.ServiceRegistrar, srv ServiceBServer) {
	// If the following call pancis, it indicates UnimplementedServiceBServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServiceB_ServiceDesc, srv)
}

func _ServiceB_BarB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceBServer).BarB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceB_BarB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceBServer).BarB(ctx, req.(*ReqB))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceB_ServiceDesc is the grpc.ServiceDesc for ServiceB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "serviceB.ServiceB",
	HandlerType: (*ServiceBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BarB",
			Handler:    _ServiceB_BarB_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/serviceB/serviceB.proto",
}
