// serviceB.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/serviceB/serviceB.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求消息：传入一个字符串参数
type ReqB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Param         string                 `protobuf:"bytes,1,opt,name=param,proto3" json:"param,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqB) Reset() {
	*x = ReqB{}
	mi := &file_api_serviceB_serviceB_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqB) ProtoMessage() {}

func (x *ReqB) ProtoReflect() protoreflect.Message {
	mi := &file_api_serviceB_serviceB_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqB.ProtoReflect.Descriptor instead.
func (*ReqB) Descriptor() ([]byte, []int) {
	return file_api_serviceB_serviceB_proto_rawDescGZIP(), []int{0}
}

func (x *ReqB) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

// 响应消息：返回一个数据字符串
type RespB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespB) Reset() {
	*x = RespB{}
	mi := &file_api_serviceB_serviceB_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespB) ProtoMessage() {}

func (x *RespB) ProtoReflect() protoreflect.Message {
	mi := &file_api_serviceB_serviceB_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespB.ProtoReflect.Descriptor instead.
func (*RespB) Descriptor() ([]byte, []int) {
	return file_api_serviceB_serviceB_proto_rawDescGZIP(), []int{1}
}

func (x *RespB) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_api_serviceB_serviceB_proto protoreflect.FileDescriptor

const file_api_serviceB_serviceB_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/serviceB/serviceB.proto\x12\bserviceB\"\x1c\n" +
	"\x04ReqB\x12\x14\n" +
	"\x05param\x18\x01 \x01(\tR\x05param\"\x1b\n" +
	"\x05RespB\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data23\n" +
	"\bServiceB\x12'\n" +
	"\x04BarB\x12\x0e.serviceB.ReqB\x1a\x0f.serviceB.RespBB&Z$go-microservices/microservices/pb;pbb\x06proto3"

var (
	file_api_serviceB_serviceB_proto_rawDescOnce sync.Once
	file_api_serviceB_serviceB_proto_rawDescData []byte
)

func file_api_serviceB_serviceB_proto_rawDescGZIP() []byte {
	file_api_serviceB_serviceB_proto_rawDescOnce.Do(func() {
		file_api_serviceB_serviceB_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_serviceB_serviceB_proto_rawDesc), len(file_api_serviceB_serviceB_proto_rawDesc)))
	})
	return file_api_serviceB_serviceB_proto_rawDescData
}

var file_api_serviceB_serviceB_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_serviceB_serviceB_proto_goTypes = []any{
	(*ReqB)(nil),  // 0: serviceB.ReqB
	(*RespB)(nil), // 1: serviceB.RespB
}
var file_api_serviceB_serviceB_proto_depIdxs = []int32{
	0, // 0: serviceB.ServiceB.BarB:input_type -> serviceB.ReqB
	1, // 1: serviceB.ServiceB.BarB:output_type -> serviceB.RespB
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_serviceB_serviceB_proto_init() }
func file_api_serviceB_serviceB_proto_init() {
	if File_api_serviceB_serviceB_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_serviceB_serviceB_proto_rawDesc), len(file_api_serviceB_serviceB_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_serviceB_serviceB_proto_goTypes,
		DependencyIndexes: file_api_serviceB_serviceB_proto_depIdxs,
		MessageInfos:      file_api_serviceB_serviceB_proto_msgTypes,
	}.Build()
	File_api_serviceB_serviceB_proto = out.File
	file_api_serviceB_serviceB_proto_goTypes = nil
	file_api_serviceB_serviceB_proto_depIdxs = nil
}
