// serviceA.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/serviceA/serviceA.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求消息：传入一个字符串参数
type ReqA struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Param         string                 `protobuf:"bytes,1,opt,name=param,proto3" json:"param,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqA) Reset() {
	*x = ReqA{}
	mi := &file_api_serviceA_serviceA_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqA) ProtoMessage() {}

func (x *ReqA) ProtoReflect() protoreflect.Message {
	mi := &file_api_serviceA_serviceA_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqA.ProtoReflect.Descriptor instead.
func (*ReqA) Descriptor() ([]byte, []int) {
	return file_api_serviceA_serviceA_proto_rawDescGZIP(), []int{0}
}

func (x *ReqA) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

// 响应消息：返回一个结果字符串
type RespA struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespA) Reset() {
	*x = RespA{}
	mi := &file_api_serviceA_serviceA_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespA) ProtoMessage() {}

func (x *RespA) ProtoReflect() protoreflect.Message {
	mi := &file_api_serviceA_serviceA_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespA.ProtoReflect.Descriptor instead.
func (*RespA) Descriptor() ([]byte, []int) {
	return file_api_serviceA_serviceA_proto_rawDescGZIP(), []int{1}
}

func (x *RespA) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_api_serviceA_serviceA_proto protoreflect.FileDescriptor

const file_api_serviceA_serviceA_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/serviceA/serviceA.proto\x12\bserviceA\"\x1c\n" +
	"\x04ReqA\x12\x14\n" +
	"\x05param\x18\x01 \x01(\tR\x05param\"\x1f\n" +
	"\x05RespA\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result23\n" +
	"\bServiceA\x12'\n" +
	"\x04FooA\x12\x0e.serviceA.ReqA\x1a\x0f.serviceA.RespAB&Z$go-microservices/microservices/pb;pbb\x06proto3"

var (
	file_api_serviceA_serviceA_proto_rawDescOnce sync.Once
	file_api_serviceA_serviceA_proto_rawDescData []byte
)

func file_api_serviceA_serviceA_proto_rawDescGZIP() []byte {
	file_api_serviceA_serviceA_proto_rawDescOnce.Do(func() {
		file_api_serviceA_serviceA_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_serviceA_serviceA_proto_rawDesc), len(file_api_serviceA_serviceA_proto_rawDesc)))
	})
	return file_api_serviceA_serviceA_proto_rawDescData
}

var file_api_serviceA_serviceA_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_serviceA_serviceA_proto_goTypes = []any{
	(*ReqA)(nil),  // 0: serviceA.ReqA
	(*RespA)(nil), // 1: serviceA.RespA
}
var file_api_serviceA_serviceA_proto_depIdxs = []int32{
	0, // 0: serviceA.ServiceA.FooA:input_type -> serviceA.ReqA
	1, // 1: serviceA.ServiceA.FooA:output_type -> serviceA.RespA
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_serviceA_serviceA_proto_init() }
func file_api_serviceA_serviceA_proto_init() {
	if File_api_serviceA_serviceA_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_serviceA_serviceA_proto_rawDesc), len(file_api_serviceA_serviceA_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_serviceA_serviceA_proto_goTypes,
		DependencyIndexes: file_api_serviceA_serviceA_proto_depIdxs,
		MessageInfos:      file_api_serviceA_serviceA_proto_msgTypes,
	}.Build()
	File_api_serviceA_serviceA_proto = out.File
	file_api_serviceA_serviceA_proto_goTypes = nil
	file_api_serviceA_serviceA_proto_depIdxs = nil
}
